// Mock data for the application

// Mock tracks
const mockTracks = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    albumCover: "images/placeholder.jpg",
    duration: "3:20",
  },
  {
    id: 2,
    title: "Save Your Tears",
    artist: "The Weeknd",
    album: "After Hours",
    albumCover: "images/placeholder.jpg",
    duration: "3:35",
  },
  {
    id: 3,
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    albumCover: "images/placeholder.jpg",
    duration: "3:23",
  },
  {
    id: 4,
    title: "Don't Start Now",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    albumCover: "images/placeholder.jpg",
    duration: "3:03",
  },
  {
    id: 5,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    albumCover: "images/placeholder.jpg",
    duration: "2:54",
  },
  {
    id: 6,
    title: "Adore You",
    artist: "Harry Styles",
    album: "Fine Line",
    albumCover: "images/placeholder.jpg",
    duration: "3:27",
  },
  {
    id: 7,
    title: "Dynamite",
    artist: "BTS",
    album: "BE",
    albumCover: "images/placeholder.jpg",
    duration: "3:19",
  },
  {
    id: 8,
    title: "Butter",
    artist: "BTS",
    album: "Butter",
    albumCover: "images/placeholder.jpg",
    duration: "2:45",
  },
  {
    id: 9,
    title: "positions",
    artist: "Ariana Grande",
    album: "Positions",
    albumCover: "images/placeholder.jpg",
    duration: "2:52",
  },
  {
    id: 10,
    title: "34+35",
    artist: "Ariana Grande",
    album: "Positions",
    albumCover: "images/placeholder.jpg",
    duration: "2:53",
  },
  {
    id: 11,
    title: "Stay",
    artist: "The Kid LAROI, Justin Bieber",
    album: "F*CK LOVE 3: OVER YOU",
    albumCover: "images/placeholder.jpg",
    duration: "2:21",
  },
  {
    id: 12,
    title: "Peaches",
    artist: "Justin Bieber",
    album: "Justice",
    albumCover: "images/placeholder.jpg",
    duration: "3:18",
  },
  {
    id: 13,
    title: "good 4 u",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    albumCover: "images/placeholder.jpg",
    duration: "2:58",
  },
  {
    id: 14,
    title: "drivers license",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    albumCover: "images/placeholder.jpg",
    duration: "4:02",
  },
  {
    id: 15,
    title: "Montero (Call Me By Your Name)",
    artist: "Lil Nas X",
    album: "MONTERO",
    albumCover: "images/placeholder.jpg",
    duration: "2:17",
  },
  {
    id: 16,
    title: "INDUSTRY BABY",
    artist: "Lil Nas X, Jack Harlow",
    album: "MONTERO",
    albumCover: "images/placeholder.jpg",
    duration: "3:32",
  },
  {
    id: 17,
    title: "Kiss Me More",
    artist: "Doja Cat, SZA",
    album: "Planet Her",
    albumCover: "images/placeholder.jpg",
    duration: "3:28",
  },
  {
    id: 18,
    title: "Need to Know",
    artist: "Doja Cat",
    album: "Planet Her",
    albumCover: "images/placeholder.jpg",
    duration: "3:31",
  },
  {
    id: 19,
    title: "Bad Habits",
    artist: "Ed Sheeran",
    album: "=",
    albumCover: "images/placeholder.jpg",
    duration: "3:51",
  },
  {
    id: 20,
    title: "Shivers",
    artist: "Ed Sheeran",
    album: "=",
    albumCover: "images/placeholder.jpg",
    duration: "3:27",
  },
]

// Mock playlists
const playlists = [
  {
    id: 1,
    name: "Discover Weekly",
    description: "Your weekly mixtape of fresh music.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(0, 3),
  },
  {
    id: 2,
    name: "Today's Top Hits",
    description: "The most popular songs right now.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(3, 5),
  },
  {
    id: 3,
    name: "Chill Vibes",
    description: "Relaxing beats to unwind to.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(5, 7),
  },
  {
    id: 4,
    name: "Rock Classics",
    description: "Rock legends & epic songs spanning the genre.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(7, 9),
  },
  {
    id: 5,
    name: "Jazz Vibes",
    description: "The perfect jazz for your day.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(9, 11),
  },
  {
    id: 6,
    name: "Hip-Hop Hits",
    description: "Today's top hip-hop tracks.",
    cover: "images/placeholder.jpg",
    creator: "iTunes Music",
    tracks: mockTracks.slice(11, 13),
  },
]

// Mock artists
const artists = [
  {
    id: 1,
    name: "The Weeknd",
    image: "images/placeholder.jpg",
    genres: ["R&B", "Pop", "Alternative R&B"],
  },
  {
    id: 2,
    name: "Dua Lipa",
    image: "images/placeholder.jpg",
    genres: ["Pop", "Dance", "Electronic"],
  },
  {
    id: 3,
    name: "Kendrick Lamar",
    image: "images/placeholder.jpg",
    genres: ["Hip-Hop", "Rap", "West Coast Hip Hop"],
  },
  {
    id: 4,
    name: "Billie Eilish",
    image: "images/placeholder.jpg",
    genres: ["Pop", "Alternative", "Electropop"],
  },
  {
    id: 5,
    name: "Taylor Swift",
    image: "images/placeholder.jpg",
    genres: ["Pop", "Country", "Folk"],
  },
  {
    id: 6,
    name: "Drake",
    image: "images/placeholder.jpg",
    genres: ["Hip-Hop", "Rap", "R&B"],
  },
]

// Mock albums
const albums = [
  {
    id: 1,
    name: "After Hours",
    artist: "The Weeknd",
    cover: "images/placeholder.jpg",
    releaseYear: 2020,
  },
  {
    id: 2,
    name: "Future Nostalgia",
    artist: "Dua Lipa",
    cover: "images/placeholder.jpg",
    releaseYear: 2020,
  },
  {
    id: 3,
    name: "DAMN.",
    artist: "Kendrick Lamar",
    cover: "images/placeholder.jpg",
    releaseYear: 2017,
  },
  {
    id: 4,
    name: "When We All Fall Asleep, Where Do We Go?",
    artist: "Billie Eilish",
    cover: "images/placeholder.jpg",
    releaseYear: 2019,
  },
  {
    id: 5,
    name: "folklore",
    artist: "Taylor Swift",
    cover: "images/placeholder.jpg",
    releaseYear: 2020,
  },
  {
    id: 6,
    name: "Certified Lover Boy",
    artist: "Drake",
    cover: "images/placeholder.jpg",
    releaseYear: 2021,
  },
]
